name: top_star
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  bot_toast: ^4.1.3
  pull_to_refresh_flutter3: ^2.0.2
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  lottie: ^2.6.0
  intl: ^0.19.0
  get: ^4.6.6
  photo_view: ^0.15.0
  permission_handler: ^11.3.1
  firebase_messaging: ^15.1.3
  device_info_plus: ^9.1.1
  flutter_spinkit: ^5.2.0
  gap: ^3.0.1
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_html: ^3.0.0-beta.2
  internet_connection_checker: ^1.0.0+1
  circular_image: ^0.0.6
  icons_plus: ^4.0.0
  smooth_page_indicator: ^1.1.0
  animated_custom_dropdown: ^3.1.1
  badges: ^3.1.2
  animations: ^2.0.7
  flutter_shakemywidget: ^1.0.5+1
  flutter_local_notifications: ^17.2.3
  modal_bottom_sheet: ^3.0.0
  dotted_border: ^2.1.0
  easy_debounce: ^2.0.3
  pin_code_fields: ^8.0.1
  gallery_saver_plus: ^3.2.0
  connectivity_widget: ^3.0.0
  segmented_control: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/lottie/
    - assets/png/
    - assets/icon/
    - assets/image/

