// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1nVgXuM3eTfxGu0YoGmYrjZ6_PzPr2Qo',
    appId: '1:479458907321:web:8e7878125d8ceaef4af768',
    messagingSenderId: '479458907321',
    projectId: 'sea-standard',
    authDomain: 'sea-standard.firebaseapp.com',
    storageBucket: 'sea-standard.appspot.com',
    measurementId: 'G-TZ93XW267Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvWeAcx0qTJ0ygim2PJAj2VSUK988uhUk',
    appId: '1:479458907321:android:7b2f9770be5172804af768',
    messagingSenderId: '479458907321',
    projectId: 'sea-standard',
    storageBucket: 'sea-standard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZwdEV1l1jSCsjSM7f2zM6MD7zChHvWoM',
    appId: '1:479458907321:ios:4ee8ef709c85df8b4af768',
    messagingSenderId: '479458907321',
    projectId: 'sea-standard',
    storageBucket: 'sea-standard.appspot.com',
    iosBundleId: 'com.seastandard.seaStandard2023',
  );
}
